name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install prerequisites
        run: |
          sudo apt update
          sudo apt install -y bash curl sudo xz-utils dpkg-dev make perl git clang

      - name: install theos
        run: |
          export THEOS="$HOME/theos"
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=$THEOS" >> "$GITHUB_ENV"
          ls -la "$HOME/theos"
          ls -la "$HOME/theos/toolchain/linux/iphone/bin" || true
          ls -la "$HOME/theos/sdks" || true

      - name: build
        run: |
          export THEOS="$HOME/theos"
          echo "THEOS=$THEOS"
          make package FINALPACKAGE=1

      - name: upload deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: packages/*.deb
          if-no-files-found: error
