name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang make git perl curl dpkg-dev xz-utils

      - name: install theos
        run: |
          git clone --recursive https://github.com/theos/theos.git "$HOME/theos"
          mkdir -p "$HOME/theos/sdks"

      - name: install iPhoneOS SDK
        run: |
          curl -L https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS9.3.sdk.tar.xz -o /tmp/iPhoneOS9.3.sdk.tar.xz
          tar -xJf /tmp/iPhoneOS9.3.sdk.tar.xz -C "$HOME/theos/sdks"
          ls -la "$HOME/theos/sdks"
          ls -la "$HOME/theos/sdks/iPhoneOS9.3.sdk"

      - name: build
        run: |
          export THEOS="$HOME/theos"
          echo "THEOS=$THEOS"
          make package FINALPACKAGE=1

      - name: upload deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: packages/*.deb
          if-no-files-found: error
